---
- hosts: all
  remote_user: root
  tasks:
    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: http://fedora-epel.mirrors.tds.net/fedora-epel//RPM-GPG-KEY-EPEL-7,http://fedora-epel.mirrors.tds.net/fedora-epel//RPM-GPG-KEY-EPEL-7Server

    - name: Add lorax-composer COPR repository
      yum_repository:
        name: lorax-composer-copr
        description: lorax-composer COPR repository
        baseurl: https://copr-be.cloud.fedoraproject.org/results/@weldr/lorax-composer/epel-7-$basearch/
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/@weldr/lorax-composer/pubkey.gpg

    - name: Add welder-web COPR repository
      yum_repository:
        name: welder-web-copr
        description: welder-web COPR repository
        baseurl: https://copr-be.cloud.fedoraproject.org/results/@weldr/welder-web/epel-7-$basearch/
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/@weldr/welder-web/pubkey.gpg

    - name: Make sure required packages are installed
      yum: name=cockpit,less,lorax,lorax-composer,composer-cli,welder-web state=latest

    - name: Setup welder-web to talk to lorax-composer via the socket
      lineinfile: dest=/usr/share/cockpit/welder/js/config.js regexp="^var welderApiPort" line="var welderApiPort=\"/run/weldr/api.socket\";" state=present

    - name: Copy example recipes
      copy: src={{ item }} dest=/var/lib/lorax/composer/recipes/
            owner=weldr group=weldr mode=0644
      with_items:
        - glusterfs.toml
        - http-server.toml
        - kubernetes.toml

    - name: Enable cockpit at boot time
      systemd: name=cockpit enabled=yes state=started

    - name: Enable lorax-composer at boot time
      systemd: name=lorax-composer.service enabled=yes state=started

    - name: Expose cockpit to the world
      firewalld:
        port: 9090/tcp
        permanent: true
        immediate: true
        state: enabled
